---
title: "Anomaly Detection"
date: "`r Sys.Date()`"
output:
    html_document:
      highlight: pygments
      code_folding: hide
      toc: true
      toc_float: true
      df_print: paged
---

```{r}
# set chunk dir to project root dir (and not script location)
knitr::opts_knit$set(root.dir = here::here())
```

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggrepel)
library(Rtsne)
library(DMwR)

data <- readr::read_rds("data/nba_2017_stats.Rds") 
```


```{r}
# list of variables that will be used to determine anomalies:
analysis_vars <- c(
  "fg_made", "fg_attempts", "three_p_made", "three_p_attempts", "ft_attempts",
  "ft_made", "reb_offensive", "reb_defensive", "assists", "turnovers",
  "steals", "blocks", "personal_fouls", "minutes"
)

# calculate z-scores
data_z <- data %>% 
  select(analysis_vars) %>%
  mutate_all(funs( (. - mean(.))/sd(.)))

# calculate mahalanobis-distance (only including analysis-variables)
mh <- mahalanobis(
  data[analysis_vars],
  center=colMeans(data[analysis_vars]),
  cov=cov(data[analysis_vars])
)

```


```{r}

# append mahalnobis distance to z-scored data
data_analysis <- data_z %>%
  mutate(mdist = mh, player=data$player, team=data$team) %>%
  select(player, team, mdist, everything()) %>%
  arrange(desc(mdist))

# determine anomalies
anomalies <- data_analysis %>% 
  top_n(10, wt=mdist)  %>% 
  pull(player)


```

```{r}

# heatmap for top 10:
data_analysis %>% 
  top_n(10, wt=mdist) %>%
  gather(stat, z_score, -player, -team, -mdist) %>% 
  ggplot(., aes(x=stat, y=reorder(player, z_score), fill=z_score)) +
  geom_tile() +
  scale_fill_viridis_c() + 
  theme(axis.text.x = element_text(angle = 45, vjust=0.5)) +
  ylab("Player") +
  xlab("Statistic")
  
```

# visualizations
```{r, message=FALSE, warning=FALSE}

# calculate tsne projections
set.seed(1337)
tsne <- Rtsne(data_analysis[-c(1:2)])

```

## tsne vis
```{r, warning=FALSE, message=FALSE}
tsne$Y %>%
  as_tibble() %>% 
  bind_cols(data_analysis %>% select(player, mdist)) %>%
  mutate(player = ifelse(player %in% c("LeBron James", "Chinanu Onuaku"), player, NA)) %>%
  rename(mahalanobis_distance = mdist) %>%
  ggplot(., aes(V1, V2, color = mahalanobis_distance)) +
  geom_point(alpha=.9) + 
  geom_label_repel(aes(label=player), box.padding=.35, point.padding=.5) +
  theme_minimal() +
  scale_color_viridis_c(begin = .1, end = .9)
```

## pca vis
```{r,  warning=FALSE, message=FALSE}

pc <- prcomp(data_analysis[-c(1:2)], center=FALSE, scale.=FALSE)

pc$x %>%
  as_tibble() %>% 
  bind_cols(data_analysis %>% select(player, mdist)) %>%
  mutate(player = ifelse(player %in% c("LeBron James", "Chinanu Onuaku"), player, NA)) %>%
  rename(mahalanobis_distance = mdist) %>%
  ggplot(., aes(PC1, PC2, color = mahalanobis_distance)) +
  geom_point(alpha=.9) + 
  geom_label_repel(aes(label=player), box.padding=.35, point.padding=.5) +
  theme_minimal() +
  scale_color_viridis_c(begin = .1, end = .9)
```

